### ISSUE TITLE
go plugin config per service/route is not applied correctly

### ISSUE THREAD

**Issue by David-Lor** [Kong/go-pluginserver#27]
Given the go-hello example plugin (https://github.com/Kong/go-plugins/blob/master/go-hello.go), and the following kong.yml (declarative configuration):

```yml
_format_version: "1.1"

services:
  - name: sample_api_1
    url: http://sample_api:80
    plugins:
      - name: go-helloworld
        config:
          message: FOO1
    routes:
      - name: sample_api_1_root
        paths: ['/sample-api-1']

  - name: sample_api_2
    url: http://sample_api:80
    plugins:
      - name: go-helloworld
        config:
          message: BAR2
    routes:
      - name: sample_api_2_root
        paths: ['/sample-api-2']

  - name: sample_api_3
    url: http://sample_api:80
    plugins:
      - name: go-helloworld
        config:
          message: BAZ3
    routes:
      - name: sample_api_3_root
        paths: ['/sample-api-3']
```

Right after starting Kong, when any endpoint is called, the message configured for that endpoint returns correctly appended to the header. But after it, when any other endpoint is called, the config.Message returns the value of the first called endpoint.

A procedure would be:

1. Start Kong
2. Get /sample-api-3 - should see config.Message = "BAZ3", sees "BAZ3"
3. Get /sample-api-2 - should see config.Message = "BAR2", sees "BAZ3"
4. Restart Kong service (container, as I'm running Kong in Docker)
5. Get /sample-api-1 - should see config.Message = "FOO1", sees "FOO1"
6. Get /sample-api-3 - should see config.Message = "BAZ3", sees "FOO1"
7. Get /sample-api-2 - should see config.Message = "BAR2", sees "FOO1"

The result is the same if the plugins are configured per route instead of per service.

My Dockerimage is like this - I download go-pluginserver and build the plugin during image creation:

```dockerfile
FROM kong:2.0.3

ENV KONG_GO_PLUGINS_DIR=/usr/local/kong/plugins-go
USER root
RUN mkdir -p $KONG_GO_PLUGINS_DIR/src
COPY ./plugins_go/* $KONG_GO_PLUGINS_DIR/src/
RUN apk --no-cache update && apk --no-cache add go musl-dev git && \
    go get github.com/Kong/go-pluginserver && \
    go build --buildmode=plugin -o $KONG_GO_PLUGINS_DIR/go-helloworld.so $KONG_GO_PLUGINS_DIR/src/go-helloworld.go && \
    rm /usr/local/bin/go-pluginserver && \
    mv /root/go/bin/go-pluginserver /usr/local/bin/ && \
    apk del go musl-dev git
USER kong
```
